version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: trading_bot_postgres
    environment:
      POSTGRES_DB: trading_bot
      POSTGRES_USER: trading_user
      POSTGRES_PASSWORD: trading_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - trading_network

  redis:
    image: redis:7-alpine
    container_name: trading_bot_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - trading_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: trading_bot_backend
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://trading_user:trading_password@postgres:5432/trading_bot
      REDIS_URL: redis://redis:6379
      UPBIT_ACCESS_KEY: ${UPBIT_ACCESS_KEY}
      UPBIT_SECRET_KEY: ${UPBIT_SECRET_KEY}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    depends_on:
      - postgres
      - redis
    volumes:
      - ./backend:/app
      - ./uploads:/app/uploads
    networks:
      - trading_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: trading_bot_frontend
    ports:
      - "3000:3000"
    environment:
      REACT_APP_API_URL: http://localhost:8000
      REACT_APP_WS_URL: ws://localhost:8000/ws
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - trading_network

volumes:
  postgres_data:
  redis_data:

networks:
  trading_network:
    driver: bridge